#!/bin/bash

#Run as a job on a HPC environment
#Takes fastq files and generates count matrix and strand specific bigwigs


#CALLING THE VARIABLES"
echo $1 # Read project folder
echo $2 # name of the samples
echo $3 # final name of sample

#load modules
. /etc/profile.d/modules.sh
module load java/jdk/1.8.0
module load igmm/apps/TrimGalore/0.5.0
module load igmm/apps/cutadapt/1.16
module load igmm/apps/STAR/2.7.1a
module load igmm/apps/samtools/1.6 
module load R
module load roslin/subread/1.5.2
module load anaconda/5.0.1
module load igmm/apps/stringtie/1.3.5


#creates folders
cd /exports/eddie/scratch/s1659595/$1/
mkdir trimmed_fastq
mkdir aln
mkdir samtools 
mkdir feature_count/
mkdir bigwig

#enter into the fastq folder
cd /exports/eddie/scratch/s1659595/$1/fastq


#TRIMMING ADAPTERS from reads
trim_galore --path_to_cutadapt cutadapt --paired -stringency 5 -length 27 -o /exports/eddie/scratch/s1659595/$1/trimmed_fastq/ -q 20 $2_R1_001.fastq $2_R2_001.fastq

cd /exports/eddie/scratch/s1659595/$1/trimmed_fastq/


#STAR 2-PASS ALIGNMENT
STAR --genomeDir /exports/csce/eddie/biology/groups/chambers/mm10/mm10_star_genome/ --readFilesIn $2_R1_001_val_1.fq $2_R2_001_val_2.fq --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --outFilterMultimapNmax 10 --outFilterMismatchNmax 10 --outFilterMismatchNoverLmax 0.3 --alignIntronMin 21 --alignIntronMax 0 --alignMatesGapMax 10000 --alignSJoverhangMin 5 --runThreadN 12 --twopassMode Basic --twopass1readsN -1 --sjdbOverhang 100 --outFileNamePrefix /exports/eddie/scratch/s1659595/$1/aln/$2_

cd /exports/eddie/scratch/s1659595/$1/aln/

#APPLY Q10 FILTER STEP AND SORT BAM by coordinates
#ON THE ALIGNED TO GENOME
samtools view -q 10 -b $2_Aligned.out.bam | samtools sort -T $2_Aligned.out.bam -o /exports/eddie/scratch/s1659595/$1/samtools/$2_genome_STAR_srt.bam -O bam - 

#ON THE ALIGNED TO TRANSCRIPTOME 
samtools view -q 10 -b $2_Aligned.toTranscriptome.out.bam | samtools sort -T $2_Aligned.toTranscriptome.out.bam -O bam -o /exports/eddie/scratch/s1659595/$1/samtools/$2_transcriptome_STAR_srt.bam -

cd /exports/eddie/scratch/s1659595/$1/samtools

#THE FOLLOWING COMMANDS RUN THE MAIN STATS FOR THE ALN SEQUENCES 
samtools flagstat $2_genome_STAR_srt.bam >  $2_genome_STAR_srt.txt
samtools flagstat $2_transcriptome_STAR_srt.bam > $2_transcriptome_STAR_srt.txt



#FEATURE_COUNTS
featureCounts $2_genome_STAR_srt.bam -C -p -t exon -g gene_id -a /exports/csce/eddie/biology/groups/chambers/mm10/mm10.refGene.gtf -o /exports/eddie/scratch/s1659595/$1/feature_count/$3_exon
#all_gene
featureCounts $2_transcriptome_STAR_srt.bam -C -p -t transcript -g gene_id -a /exports/csce/eddie/biology/groups/chambers/mm10/mm10.refGene.gtf -o /exports/eddie/scratch/s1659595/$1/feature_count/$3_gene


cd /exports/eddie/scratch/s1659595/$1/samtools
stringtie $2_transcriptome_STAR_srt.bam -B -e -G /exports/csce/eddie/biology/groups/chambers/mm10/mm10.refGene.gtf -o /exports/eddie/scratch/s1659595/$1/feature_count/$3_gene_stringtie
stringtie $2_genome_STAR_srt.bam -B -e -G /exports/csce/eddie/biology/groups/chambers/mm10/mm10.refGene.gtf -o /exports/eddie/scratch/s1659595/$1/feature_count/$3_genome_stringtie



cd /exports/eddie/scratch/s1659595/$1/samtools
#PRODUCE BIGWIG
#SPLIT LIBRARIES BY STRAND: NOTE, LIBRARIES PRODUCED AT WISTAR ARE REVERSE STRANDED  - check if this is true also for Edi data
~/scripts/split_PE_bam.sh $2_genome_STAR_srt.bam   /exports/eddie/scratch/s1659595/$1/bigwig/


cd /exports/eddie/scratch/s1659595/$1/bigwig

#INDEX BAM
samtools index $2_genome_STAR_srt_rev.bam
samtools index $2_genome_STAR_srt_fwd.bam

cd /exports/eddie/scratch/s1659595/$1/bigwig
#PRODUCE BIGWIG
#SPLIT LIBRARIES BY STRAND: NOTE, LIBRARIES PRODUCED AT WISTAR ARE REVERSE STRANDED  - check if this is true also for Edi data

#BIGWIGS:
source activate python
bamCoverage --bam $2_genome_STAR_srt_fwd.bam -o $3_genome_STAR_srt_FOR.bw
bamCoverage --bam $2_genome_STAR_srt_rev.bam -o $3_genome_STAR_srt_REV.bw
source deactivate python
